<NotepadPlus>
    <Project name="Avant Content">
        <Folder name="assets">
            <Folder name="css">
                <File name="assets\css\avant.css" />
            </Folder>
            <Folder name="dist">
                <Folder name="bootstrap-3.3.7">
                    <Folder name="css">
                        <File name="assets\dist\bootstrap-3.3.7\css\bootstrap-theme.css" />
                        <File name="assets\dist\bootstrap-3.3.7\css\bootstrap-theme.css.map" />
                        <File name="assets\dist\bootstrap-3.3.7\css\bootstrap-theme.min.css" />
                        <File name="assets\dist\bootstrap-3.3.7\css\bootstrap-theme.min.css.map" />
                        <File name="assets\dist\bootstrap-3.3.7\css\bootstrap.css" />
                        <File name="assets\dist\bootstrap-3.3.7\css\bootstrap.css.map" />
                        <File name="assets\dist\bootstrap-3.3.7\css\bootstrap.min.css" />
                        <File name="assets\dist\bootstrap-3.3.7\css\bootstrap.min.css.map" />
                    </Folder>
                    <Folder name="fonts">
                        <File name="assets\dist\bootstrap-3.3.7\fonts\glyphicons-halflings-regular.eot" />
                        <File name="assets\dist\bootstrap-3.3.7\fonts\glyphicons-halflings-regular.svg" />
                        <File name="assets\dist\bootstrap-3.3.7\fonts\glyphicons-halflings-regular.ttf" />
                        <File name="assets\dist\bootstrap-3.3.7\fonts\glyphicons-halflings-regular.woff" />
                        <File name="assets\dist\bootstrap-3.3.7\fonts\glyphicons-halflings-regular.woff2" />
                    </Folder>
                    <Folder name="js">
                        <File name="assets\dist\bootstrap-3.3.7\js\bootstrap.js" />
                        <File name="assets\dist\bootstrap-3.3.7\js\bootstrap.min.js" />
                        <File name="assets\dist\bootstrap-3.3.7\js\npm.js" />
                    </Folder>
                </Folder>
            </Folder>
            <Folder name="favicons">
                <File name="assets\favicons\android-icon-144x144.png" />
                <File name="assets\favicons\android-icon-192x192.png" />
                <File name="assets\favicons\android-icon-36x36.png" />
                <File name="assets\favicons\android-icon-48x48.png" />
                <File name="assets\favicons\android-icon-72x72.png" />
                <File name="assets\favicons\android-icon-96x96.png" />
                <File name="assets\favicons\apple-icon-114x114.png" />
                <File name="assets\favicons\apple-icon-120x120.png" />
                <File name="assets\favicons\apple-icon-144x144.png" />
                <File name="assets\favicons\apple-icon-152x152.png" />
                <File name="assets\favicons\apple-icon-180x180.png" />
                <File name="assets\favicons\apple-icon-57x57.png" />
                <File name="assets\favicons\apple-icon-60x60.png" />
                <File name="assets\favicons\apple-icon-72x72.png" />
                <File name="assets\favicons\apple-icon-76x76.png" />
                <File name="assets\favicons\apple-icon-precomposed.png" />
                <File name="assets\favicons\apple-icon.png" />
                <File name="assets\favicons\browserconfig.xml" />
                <File name="assets\favicons\favicon-16x16.png" />
                <File name="assets\favicons\favicon-32x32.png" />
                <File name="assets\favicons\favicon-96x96.png" />
                <File name="assets\favicons\favicon.ico" />
                <File name="assets\favicons\manifest.json" />
                <File name="assets\favicons\ms-icon-144x144.png" />
                <File name="assets\favicons\ms-icon-150x150.png" />
                <File name="assets\favicons\ms-icon-310x310.png" />
                <File name="assets\favicons\ms-icon-70x70.png" />
            </Folder>
            <Folder name="images">
                <File name="assets\images\beawriter.jpg" />
                <File name="assets\images\bluish.jpg" />
                <File name="assets\images\desk.png" />
                <File name="assets\images\hand_writing.jpg" />
                <File name="assets\images\hand_writing_plain.jpg" />
                <File name="assets\images\hyph.jpg" />
                <File name="assets\images\Kharei2.jpg" />
                <File name="assets\images\Konso.jpg" />
                <File name="assets\images\pencil.png" />
                <File name="assets\images\pencilbook.jpg" />
                <File name="assets\images\typewriter_w.jpg" />
                <File name="assets\images\userblack.png" />
                <File name="assets\images\userblue.png" />
                <File name="assets\images\userwhite.png" />
                <File name="assets\images\vintage_pens_writing.jpg" />
                <File name="assets\images\white.jpg" />
                <File name="assets\images\write.png" />
            </Folder>
            <Folder name="js">
                <File name="assets\js\jquery-3.1.1.min.js" />
                <File name="assets\js\jquery-numerator.js" />
                <File name="assets\js\jquery.counterup.min.js" />
            </Folder>
        </Folder>
        <Folder name="temp">
            <File name="temp\login.php" />
            <File name="temp\signin.php" />
            <File name="temp\signup.php" />
            <File name="temp\submit.php" />
        </Folder>
        <File name=".project" />
        <File name="about.php" />
        <File name="check.js" />
        <File name="footer.php" />
        <File name="header.php" />
        <File name="index.php" />
        <File name="main_class.php" />
        <File name="order.php" />
        <File name="Web.config" />
    </Project>
    <Project name="Class Projects">
        <Folder name="App_Data" />
        <Folder name="bin">
            <Folder name="AMD64">
                <Folder name="Microsoft.VC90.CRT">
                    <File name="C:\Users\vmach\OneDrive\Documents\My Web Sites\EmptySite1\bin\AMD64\Microsoft.VC90.CRT\Microsoft.VC90.CRT.manifest" />
                    <File name="C:\Users\vmach\OneDrive\Documents\My Web Sites\EmptySite1\bin\AMD64\Microsoft.VC90.CRT\msvcr90.dll" />
                    <File name="C:\Users\vmach\OneDrive\Documents\My Web Sites\EmptySite1\bin\AMD64\Microsoft.VC90.CRT\README_ENU.txt" />
                </Folder>
                <File name="C:\Users\vmach\OneDrive\Documents\My Web Sites\EmptySite1\bin\AMD64\sqlceca40.dll" />
                <File name="C:\Users\vmach\OneDrive\Documents\My Web Sites\EmptySite1\bin\AMD64\sqlcecompact40.dll" />
                <File name="C:\Users\vmach\OneDrive\Documents\My Web Sites\EmptySite1\bin\AMD64\sqlceer40EN.dll" />
                <File name="C:\Users\vmach\OneDrive\Documents\My Web Sites\EmptySite1\bin\AMD64\sqlceme40.dll" />
                <File name="C:\Users\vmach\OneDrive\Documents\My Web Sites\EmptySite1\bin\AMD64\sqlceqp40.dll" />
                <File name="C:\Users\vmach\OneDrive\Documents\My Web Sites\EmptySite1\bin\AMD64\sqlcese40.dll" />
            </Folder>
            <Folder name="System.Data.SqlServerCe.Entity">
                <File name="C:\Users\vmach\OneDrive\Documents\My Web Sites\EmptySite1\bin\System.Data.SqlServerCe.Entity\System.Data.SqlServerCe.Entity.dll" />
            </Folder>
            <Folder name="X86">
                <Folder name="Microsoft.VC90.CRT">
                    <File name="C:\Users\vmach\OneDrive\Documents\My Web Sites\EmptySite1\bin\X86\Microsoft.VC90.CRT\Microsoft.VC90.CRT.manifest" />
                    <File name="C:\Users\vmach\OneDrive\Documents\My Web Sites\EmptySite1\bin\X86\Microsoft.VC90.CRT\msvcr90.dll" />
                    <File name="C:\Users\vmach\OneDrive\Documents\My Web Sites\EmptySite1\bin\X86\Microsoft.VC90.CRT\README_ENU.txt" />
                </Folder>
                <File name="C:\Users\vmach\OneDrive\Documents\My Web Sites\EmptySite1\bin\X86\sqlceca40.dll" />
                <File name="C:\Users\vmach\OneDrive\Documents\My Web Sites\EmptySite1\bin\X86\sqlcecompact40.dll" />
                <File name="C:\Users\vmach\OneDrive\Documents\My Web Sites\EmptySite1\bin\X86\sqlceer40EN.dll" />
                <File name="C:\Users\vmach\OneDrive\Documents\My Web Sites\EmptySite1\bin\X86\sqlceme40.dll" />
                <File name="C:\Users\vmach\OneDrive\Documents\My Web Sites\EmptySite1\bin\X86\sqlceqp40.dll" />
                <File name="C:\Users\vmach\OneDrive\Documents\My Web Sites\EmptySite1\bin\X86\sqlcese40.dll" />
            </Folder>
            <File name="C:\Users\vmach\OneDrive\Documents\My Web Sites\EmptySite1\bin\System.Data.SqlServerCe.dll" />
        </Folder>
        <File name="C:\Users\vmach\OneDrive\Documents\My Web Sites\EmptySite1\array.php" />
        <File name="C:\Users\vmach\OneDrive\Documents\My Web Sites\EmptySite1\array2.php" />
        <File name="C:\Users\vmach\OneDrive\Documents\My Web Sites\EmptySite1\case.php" />
        <File name="C:\Users\vmach\OneDrive\Documents\My Web Sites\EmptySite1\day.php" />
        <File name="C:\Users\vmach\OneDrive\Documents\My Web Sites\EmptySite1\form.php" />
        <File name="C:\Users\vmach\OneDrive\Documents\My Web Sites\EmptySite1\info.php" />
        <File name="C:\Users\vmach\OneDrive\Documents\My Web Sites\EmptySite1\insert.php" />
        <File name="C:\Users\vmach\OneDrive\Documents\My Web Sites\EmptySite1\marks.php" />
        <File name="C:\Users\vmach\OneDrive\Documents\My Web Sites\EmptySite1\web.config" />
    </Project>
</NotepadPlus>
